<?php

/**
 * @file
 * Contains schema_article.module.
 */

function planet_structured_data_page_attachments_alter(array &$attachments) {
  $node = \Drupal::routeMatch()->getParameter('node');

  $current_path = \Drupal::service('path.current')->getPath();
  $current_path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);

  if (!str_starts_with($current_path_alias, '/blog')) {
    foreach ($attachments['#attached']['html_head'] as $key => $attachment) {
      if (str_starts_with($attachment[1],'schema_article')) {
        unset($attachments['#attached']['html_head'][$key]);
      }
    }
  }

}
