<?php

use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function planet_accept_payments_theme(): array {
  return [
    'node__accept_payments' => [
      'template' => 'node--accept-payments',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function planet_accept_payments_theme_suggestions_node_alter(array &$suggestions, array &$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $route_object = \Drupal::routeMatch()->getRouteObject();
  $current_url = \Drupal::service('path.current')->getPath();
  $alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_url);
  $is_admin_page = \Drupal::service('router.admin_context')->isAdminRoute($route_object);

  if (!$node or !($node instanceof NodeInterface)) {
    return;
  }

  $node_translation_service = \Drupal::service('planet_core.node_translation_service');


  if (!$is_admin_page) {
    $translations = $node_translation_service->getTranslationArrWithoutPrefixes('/accept-payments');
    $lang_id = $node_translation_service->determineTheLangId();

    if ($translations && in_array($alias, $translations) || in_array("/$lang_id" . $alias, $translations)) {
      $variables['cards'] = \Drupal::service("planet_accept_payments.service")->getCards();
      $suggestions[] = 'node__accept_payments';
    }
  }

}

function planet_accept_payments_preprocess_node(array &$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $node_translation_service = \Drupal::service('planet_core.node_translation_service');
  $route_object = \Drupal::routeMatch()->getRouteObject();
  $current_url = \Drupal::service('path.current')->getPath();
  $alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_url);
  $is_admin_page = \Drupal::service('router.admin_context')->isAdminRoute($route_object);

  if (!$node or !($node instanceof NodeInterface)) {
    return;
  }

  if (!$is_admin_page) {
    $translations = $node_translation_service->getTranslationArrWithoutPrefixes('/accept-payments');
    $lang_id = $node_translation_service->determineTheLangId();

    if ($translations && in_array($alias, $translations) || in_array("/$lang_id" . $alias, $translations)) {
      $variables['brands'] = \Drupal::service('planet_accept_payments.service')->getBrandsWeWorkWith();
    }
  }
}

/**
 * Implements hook_preprocess_hook().
 */
function planet_accept_payments_preprocess_page(&$variables) {
  $route_object = \Drupal::routeMatch()->getRouteObject();
  $current_url = \Drupal::service('path.current')->getPath();
  $alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_url);
  $is_admin_page = \Drupal::service('router.admin_context')->isAdminRoute($route_object);
  $node_translation_service = \Drupal::service('planet_core.node_translation_service');

  if (!$is_admin_page) {
    $translations = $node_translation_service->getTranslationArrWithoutPrefixes('/accept-payments');
    $lang_id = $node_translation_service->determineTheLangId();

    if ($translations && in_array($alias, $translations) || in_array("/$lang_id" . $alias, $translations)) {
      $variables['#attached']['library'][] = 'planet_accept_payments/tailwind';
      $variables['#attached']['library'][] = 'planet_accept_payments/planet_accept_payments';
      $variables['#attached']['library'][] = 'planet_core/brands-we-work-with';
      $variables['#attached']['library'][] = 'planet_core/swiper-bundle';
    }
  }
}
