<?php

/**
 * @file
 * Primary module hooks for planet_node_updater module.
 */

/**
 * Implements hook_theme().
 */
function planet_node_updater_theme(): array {
  $array = [
    'block__system_main_block_product_pages' => [
      'template' => 'block--system-main-block-product-pages',
      'base hook' => 'node',
    ],
    'page__contact_sales' => [
      'template' => 'page--contact-sales',
      'base hook' => 'page',
    ],
  ];

  return $array;

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function planet_node_updater_theme_suggestions_block_alter(array &$suggestions, array &$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $route_object = \Drupal::routeMatch()->getRouteObject();
  $is_admin_page = \Drupal::service('router.admin_context')->isAdminRoute($route_object);

  if (!$node || $is_admin_page) {
    return;
  }

  $type = $node->getType();

  if ($type === 'page' && $variables['elements']['#plugin_id'] === 'system_main_block') {
    if ($node->get('field_is_product_page')) {
      $is_product_page = $node->get('field_is_product_page')->getValue()[0]['value'];

      if ($is_product_page == '1') {
        $suggestions[] = 'block__system_main_block_product_pages';
        $variables['html_content'] = $node->get('field_html_content')->getValue()[0]['value'];
      }
    }
  }

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function planet_node_updater_theme_suggestions_page_alter(array &$suggestions, array &$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $route_object = \Drupal::routeMatch()->getRouteObject();
  $is_admin_page = \Drupal::service('router.admin_context')->isAdminRoute($route_object);
  if (!$is_admin_page && $node->id() == 376) {
    $suggestions[] = 'page__contact_sales';
    $variables['html_content'] = $node->get('field_html_content')->getValue()[0]['value'];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function planet_node_updater_preprocess_page(array &$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $route_object = \Drupal::routeMatch()->getRouteObject();
  $is_admin_page = \Drupal::service('router.admin_context')->isAdminRoute($route_object);

  if ($node && $node->id() === '351') {
    $variables['#attached']['library'][] = 'planet_node_updater/planet_node_updater';
  }

  if (!$is_admin_page && $node && $node->id() === '41') {
    $variables['#attached']['library'][] = 'planet_node_updater/planet_node_updater_contact';
  }

  if (!$is_admin_page && $node && $node->id() === '376') {
    $form = \Drupal::entityTypeManager()->getStorage('webform')->load('get_in_touch_dynamic')->getSubmissionForm();
    $variables['form'] = $form;
    $variables['#attached']['library'][] = 'planet_node_updater/planet_node_updater_contact_sales';
  }
}
