<?php

/**
 * @file
 * Primary module hooks for planet_node_updater module.
 */

use Drupal\cohesion_elements\Entity\CohesionLayout;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 */
function planet_node_updater_theme(): array {
  $array = [
    'block__system_main_block_contact_sales' => [
      'template' => 'block--system-main-block-contact-sales',
      'base hook' => 'block',
    ],
  ];

  return $array;

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function planet_node_updater_theme_suggestions_block_alter(array &$suggestions, array &$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $route_object = \Drupal::routeMatch()->getRouteObject();
  $is_admin_page = \Drupal::service('router.admin_context')->isAdminRoute($route_object);

  if (!$node || $is_admin_page) {
    return;
  }

  $type = $node->getType();

  if ($type === 'page' && $variables['elements']['#plugin_id'] === 'system_main_block') {
    if ($node->get('field_is_product_page') && !empty($node->get('field_is_product_page')->getValue())) {
      $is_product_page = $node->get('field_is_product_page')->getValue()[0]['value'];

      if (!$is_admin_page && $node && $node->id() == 376) {
        $suggestions[] = 'block__system_main_block_contact_sales';
        $variables['html_content'] = $node->get('field_html_content')->getValue()[0]['value'];
        $variables['brands'] = \Drupal::service('planet_core.case_studies_helper')->getBrandsWeWorkWith();
        $variables['node'] = $node;
        $form = \Drupal::entityTypeManager()->getStorage('webform')->load('get_in_touch_dynamic')->getSubmissionForm();
        $variables['form'] = $form;
      }
    }
  }
}

/**
 * Implements hook_preprocess_block().
 */
function planet_node_updater_preprocess_block(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $route_object = \Drupal::routeMatch()->getRouteObject();
  $is_admin_page = \Drupal::service('router.admin_context')->isAdminRoute($route_object);

  if (!$is_admin_page && $node && $node->id() == 376) {
    $variables['#attached']['library'][] = 'planet_node_updater/planet_node_updater_contact_sales';
    $variables['#attached']['library'][] = 'planet_core/brands-we-work-with';
    $variables['#attached']['library'][] = 'planet_core/swiper-bundle';
  }
}

/**
 * Implements hook_entity_presave().
 */

function planet_node_updater_entity_presave(EntityInterface $entity) {
  // Ensure the entity is a translatable type and supports translations.
  if ($entity instanceof CohesionLayout) {
    $field_to_check = 'default_langcode';

    // First, check the base entity (non-translated).
    if ($entity->hasField($field_to_check) && $entity->get($field_to_check)->isEmpty()) {
      $current_language = \Drupal::languageManager()->getCurrentLanguage()->getId();
      $default_value = ($current_language === 'en') ? true : false;
      $entity->set($field_to_check, $default_value);
    }

    // Then, check translations if they exist.
    if ($entity->isTranslatable()) {
      $translations = $entity->getTranslationLanguages();

      // Iterate over translations if any exist.
      foreach ($translations as $language_code => $language) {
        $translated_entity = $entity->getTranslation($language_code);

        // Check if the field is NULL in the translation.
        if ($translated_entity->hasField($field_to_check) && $translated_entity->get($field_to_check)->isEmpty()) {
          $value = ($language_code === 'en') ? true : false;
          $translated_entity->set($field_to_check, $value);
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function planet_node_updater_preprocess_node(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $route_object = \Drupal::routeMatch()->getRouteObject();
  $is_admin_page = \Drupal::service('router.admin_context')->isAdminRoute($route_object);

  if (!$is_admin_page && $node && $node->id() == 41) {
    $variables['#attached']['library'][] = 'planet_node_updater/planet_node_updater_contact';

  }
}
