-
  type: cohesion_website_settings
  export:
    uuid: da7782e0-d06b-4237-8d47-4c347d09d636
    langcode: en
    status: true
    dependencies: {  }
    label: 'Base unit settings'
    id: base_unit_settings
    json_values: '{"baseFontSize":{"value":16},"baseFontSizeEnable":true,"defaultUnitConversion":"rem"}'
    json_mapper: '{}'
    last_entity_update: entityupdate_0035
    locked: false
    modified: true
    selectable: true
-
  type: cohesion_website_settings
  export:
    uuid: c0a4a07b-1699-41d0-936f-110f7967c922
    langcode: en
    status: true
    dependencies:
      config:
        - cohesion_website_settings.cohesion_color.planet-black
        - cohesion_website_settings.cohesion_font_stack.tt-commons
    label: 'Default font settings'
    id: default_font_settings
    json_values: '{"defaultFontStack":"$coh-font-tt-commons","color":{"link":true,"value":{"hex":"#000000","rgba":"rgba(0, 0, 0, 1)"},"wysiwyg":true,"name":"Planet Black","uid":"planet-black","class":".coh-color-planet-black","variable":"$coh-color-planet-black","inuse":true}}'
    json_mapper: '{}'
    last_entity_update: entityupdate_0035
    locked: false
    modified: true
    selectable: true
-
  type: cohesion_website_settings
  export:
    uuid: 7ee35d4e-e424-434c-9e2c-3604655a10f9
    langcode: en
    status: true
    dependencies: {  }
    label: 'Responsive grid settings'
    id: responsive_grid_settings
    json_values: '{"gridType":"desktop-first","columns":12,"breakpoints":{"xl":{"width":1600,"innerGutter":30,"outerGutter":64,"widthType":"fixed","previewColumns":12,"label":"Television","class":"coh-icon-television","iconHex":"F26C","boxedWidth":1472},"lg":{"width":1280,"innerGutter":32,"outerGutter":64,"widthType":"fluid","previewColumns":12,"label":"Desktop","class":"coh-icon-desktop","iconHex":"F108","boxedWidth":1152},"md":{"width":1024,"innerGutter":24,"outerGutter":48,"widthType":"fluid","previewColumns":12,"label":"Laptop","class":"coh-icon-laptop","iconHex":"F109","boxedWidth":928},"sm":{"width":768,"innerGutter":24,"outerGutter":48,"widthType":"fluid","previewColumns":6,"label":"Tablet","class":"coh-icon-tablet","iconHex":"F10A","boxedWidth":672},"ps":{"width":565,"innerGutter":24,"outerGutter":24,"widthType":"fluid","previewColumns":6,"label":"Mobile landscape","class":"coh-icon-mobile-landscape","iconHex":"E91E","boxedWidth":517},"xs":{"width":320,"innerGutter":24,"outerGutter":24,"widthType":"fluid","mobilePlaceholderWidth":320,"mobilePlaceholderType":"fluid","previewColumns":6,"label":"Mobile","class":"coh-icon-mobile","iconHex":"F10B","boxedWidth":272}}}'
    json_mapper: '{}'
    last_entity_update: entityupdate_0035
    locked: false
    modified: true
    selectable: true
