<?php
//
///**
// * @file
// * Primary module hooks for Planet HTML Sitemap module.
// */
//
///**
// * Implements hook_theme().
// */
//function planet_html_sitemap_theme() {
//  $current_url = \Drupal::service('path.current')->getPath();
//  $path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_url);
//
//  if ($path_alias === '/sitemap') {
//    return [
//      'node__sitemap' => [
//        'template' => 'node--sitemap',
//        'variables' => [
//          'term_tree' => \Drupal::service('planet_html_sitemap.helper')->buildTree(),
//        ],
//        'base hook' => 'node',
//      ],
//    ];
//  }
//
//}
//
//
///**
// * Implements hook_preprocess_HOOK() for node.
// */
//function planet_html_sitemap_preprocess_node(&$variables) {
//  //  \Drupal::logger('planet_html_sitemap')->notice('1');
//  if (isset($variables['theme_hook_original'])) {
//    if ($variables['theme_hook_original'] === 'node') {
//      $current_url = \Drupal::service('path.current')->getPath();
//
//      $path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_url);
//
//      if ($path_alias === '/sitemap') {
//        \Drupal::logger('planet_html_sitemap')->notice('4');
//        $variables['term_tree'] = \Drupal::service('planet_html_sitemap.helper')->buildTree();
//        $variables['#attached']['library'][] = 'planet_html_sitemap/planet_html_sitemap';
//      }
//    }
//  }
//}
//
//function planet_html_sitemap_theme_suggestions_node_alter(&$suggestions, $variables) {
//  $url = \Drupal::service('path.current')->getPath();
//  $path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($url);
//
//  if ($path_alias === '/sitemap') {
//    // Sanitize the path alias to create a valid template name.
//    $sanitized_path_alias = str_replace(['/', '-'], ['__', '__'], ltrim($path_alias, '/'));
//
//    // Add the sanitized path alias as a new suggestion.
//    $suggestions[] = 'node__' . $sanitized_path_alias;
//  }
//}
//
