<?php

/**
 * @file
 * Primary module hooks for Planet HTML Sitemap module.
 */

/**
 * Implements hook_theme().
 */
function planet_html_sitemap_theme() {
  $current_url = \Drupal::service('path.current')->getPath();
  $path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_url);

  if ($path_alias === '/sitemap') {
    return [
      'sitemap_html' => [
        'template' => 'sitemap-html',
        'base hook' => 'node',
        'variables' => [
          'term_tree' => [],
        ],
      ],
    ];
  }

}

/**
 * Implements hook_preprocess_HOOK() for node.
 */
function planet_html_sitemap_preprocess(&$variables) {
  if (isset($variables['theme_hook_original'])) {
    if ($variables['theme_hook_original'] === 'node') {
      $current_url = \Drupal::service('path.current')->getPath();

      $path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_url);

      if ($path_alias === '/sitemap') {
        $variables['term_tree'] = \Drupal::service('planet_html_sitemap.helper')->buildTree();
        $variables['#attached']['library'][] = 'planet_html_sitemap/planet_html_sitemap';
      }
    }
  }
}

//Suggestions preprocess
function planet_html_sitemap_theme_suggestions_node_alter(&$suggestions, &$variables) {
  $url = \Drupal::service('path.current')->getPath();
  $path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($url);

  if ($path_alias === '/sitemap') {
    $suggestions[] = 'sitemap_html';
  }
}


function planet_html_sitemap_simple_sitemap_links_alter(&$links, $sitemap) {
  foreach ($links as $key => $link) {
    unset($links[$key]['changefreq']);
    $priority = false;
    $links[$key]['priority'] = $priority;
  }
}
