<?php

/**
 * @file
 * Primary module hooks for planet_header module.
 */

/**
 * Implements hook_theme().
 */
function planet_header_theme() {
  $current_url = \Drupal::service('path.current')->getPath();

  $is_admin_page = \Drupal::service('router.admin_context')->isAdminRoute(\Drupal::routeMatch()->getRouteObject());

  // We do not want to display the header block on user pages or admin pages.
  if (!str_starts_with($current_url, '/user') || !$is_admin_page) {
    return [
      'block__planet_header_block' => [
        'variables' => [
          'data' => [],
        ]
      ],
    ];
  }
}

function planet_header_preprocess_page(&$variables) {
  $current_url = \Drupal::service('path.current')->getPath();

  $is_admin_page = \Drupal::service('router.admin_context')->isAdminRoute(\Drupal::routeMatch()->getRouteObject());

  // We do not want to display the header block on user pages or admin pages.
  if (!str_starts_with($current_url, '/user') && !$is_admin_page) {
    $variables['#attached']['library'][] = 'planet_header/planet_header';
  }
}
