<?php

/**
 * @file
 * Primary module hooks for planet_customer_resources_library module.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function planet_customer_resources_library_theme() {
  return [
    'node__planet_customer_resources_library' => [
      'template' => 'node--planet-customer-resources-library',
      'base hook' => 'node',
    ],
    'views_view__planet_customer_resources_library' => [
      'template' => 'views-view--planet-customer-resources-library',
      'base hook' => 'views_view',
    ],
    'block__views_exposed_filter_block__planet_resources_block_2' => [
      'template' => 'block--views-exposed-filter-block--planet-resources-block-2',
      'base hook' => 'block',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function planet_customer_resources_library_preprocess_page(array &$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');

  if ($node) {
    $route_object = \Drupal::routeMatch()->getRouteObject();
    $is_admin = \Drupal::service('router.admin_context')->isAdminRoute($route_object);

    $current_url = \Drupal::service('path.current')->getPath();
    $alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_url);

    // It's better to check on alias than node ID.
    if ($alias === '/customer-resources-library' && !$is_admin) {
      $variables['#attached']['library'][] = 'planet_customer_resources_library/tailwind';

    }
  }

}

function planet_customer_resources_library_theme_suggestions_node_alter(array &$suggestions, array &$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');

  if (!$node or !($node instanceof NodeInterface)) {
    return;
  }

  $node_translation_service = \Drupal::service('planet_core.node_translation_service');
  $route_object = \Drupal::routeMatch()->getRouteObject();
  $current_url = \Drupal::service('path.current')->getPath();
  $alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_url);
  $is_admin_page = \Drupal::service('router.admin_context')->isAdminRoute($route_object);

  if (!$is_admin_page) {
    if ($node->id() == '5627') {
      $suggestions[] = 'node__planet_customer_resources_library';
    }

    $translations = $node_translation_service->buildTranslationArrayForNode($node);
    $lang_id = \Drupal::languageManager()->getCurrentLanguage()->getId();

    if ($alias === '/customer-resources-library') {
      if (in_array($alias, $translations) || in_array("/$lang_id" . $alias, $translations)) {
        $suggestions[] = 'node__planet_customer_resources_library';
      }
    }
  }
}

function planet_customer_resources_library_theme_suggestions_views_view_alter(array &$suggestions, array &$variables) {
  $view_id = $variables['view']->id();
  $current_display = $variables['view']->current_display;

  if ($view_id === 'planet_resources' && $current_display === 'block_2') {
    $nids = array_map(function ($row) {
      return $row->_entity->id();
    }, $variables['view']->result);

    $resources = \Drupal::service('planet_customer_resources_library.service')->getResourcesDataArray($nids);
    $variables['resources'] = $resources;
    $suggestions[] = 'views_view__planet_customer_resources_library';
  }

}
