<?php

/**
 * @file
 * Primary module hooks for planet_footer module.
 */

/**
 * Implements hook_theme().
 */
function planet_footer_theme() {
  $current_url = \Drupal::service('path.current')->getPath();

  $is_admin_page = \Drupal::service('router.admin_context')
    ->isAdminRoute(\Drupal::routeMatch()->getRouteObject());

  // We do not want to display the footer block on user pages or admin pages.
  if (!str_starts_with($current_url, '/user') && !$is_admin_page) {
    return [
      'block__planet_footer_block' => [],
      'block__planet_legal_block' => [],
    ];
  }
}

/**
 * Implements hook_preprocess_page().
 */
function planet_footer_preprocess_page(&$variables) {
  $current_url = \Drupal::service('path.current')->getPath();

  $is_admin_page = \Drupal::service('router.admin_context')
    ->isAdminRoute(\Drupal::routeMatch()->getRouteObject());

  // We do not want to display the footer block on user pages or admin pages.
  if (!str_starts_with($current_url, '/user') && !$is_admin_page) {
    $variables['#attached']['library'][] = 'planet_footer/planet_footer';
  }
}
