<?php

/**
 * @file
 * Custom hooks functions for the planet_core module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_html().
 *
 * Changes the title of the user page.
 */
function planet_core_preprocess_html(&$variables): void {
  $routeName = \Drupal::routeMatch()->getRouteName();
  if ($routeName === 'entity.user.canonical') {
    $variables['head_title']['title'] = '';
  }
}

/**
 * Implements hook_form_alter().
 *
 * @codeCoverageIgnore
 */
function planet_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add UTM to the get in touch webform.
  if (str_contains($form_id, "webform_submission_get_in_touch")) {
    // Get X-Acquia-Stripped-Query header.
    // This is because of acquia varnish.
    $request = \Drupal::requestStack()->getCurrentRequest();
    $xAcquiaStrippedQuery = $request->headers->get('X-Acquia-Stripped-Query');

    if (!empty($xAcquiaStrippedQuery)) {
      parse_str($xAcquiaStrippedQuery, $get_array);
      if (is_array($get_array) && !empty($get_array)) {
        $form['elements']['utm_source']['#default_value'] = (isset($get_array['utm_source'])) ? $get_array['utm_source'] : '';
        $form['elements']['utm_medium']['#default_value'] = (isset($get_array['utm_medium'])) ? $get_array['utm_medium'] : '';
        $form['elements']['utm_campaign']['#default_value'] = (isset($get_array['utm_campaign'])) ? $get_array['utm_campaign'] : '';
        $form['elements']['utm_content']['#default_value'] = (isset($get_array['utm_content'])) ? $get_array['utm_content'] : '';
        $form['elements']['utm_term']['#default_value'] = (isset($get_array['utm_term'])) ? $get_array['utm_term'] : '';
      }
    }
  }
}

/**
 * Implements hook_form_views_exposed_form_alter().
 *
 * Creates region/country dependent filter.
 */
function planet_core_form_views_exposed_form_alter(&$form, &$form_state): void {
  if ($form['#id'] === 'views-exposed-form-companies-registered-companies') {
    unset($form['region']['#options']['All']);

    $input = $form_state->getUserInput();
    $selectedRegion = $input['region'];
    if ($selectedRegion === 'All') {
      $selectedRegion = array_key_first($form['region']['#options']);
    }

    $countries = _get_associative_countries_with_region($selectedRegion);
    $form['country']['#options'] = $countries;

    $form['#attached']['library'][] = 'planet_sitestudio_custom_elements/registeredCompanies';
  }
}

/**
 * Gets countries associated with the region.
 */
function _get_associative_countries_with_region(string $regionId): array {
  $countries = [];
  $countries['All'] = 'All';
  $vid = 'countries';

  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid, 0, NULL, TRUE);
  if ($regionId != 'All') {
    $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties([
      'vid' => $vid,
      'field_region' => $regionId,
    ]);
  }

  foreach ($terms as $term) {
    $countries[$term->id()] = $term->label();
  }

  return $countries;
}
