<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function planet_case_studies_theme(): array {
  $array = [
    'node__case_studies_landing' => [
      'template' => 'node--case-studies-landing',
      'base hook' => 'node',
      'variables' => []
    ],
    'node__case_studies' => [
      'template' => 'node--case-studies',
      'base hook' => 'node',
      'variables' => []
    ],
    'select__case_studies' => [
      'template' => 'select--case-studies',
      'base hook' => 'select',
      'variables' => []
    ],
    'block__case_studies_reviews' => [
      'template' => 'block--case-studies-reviews',
      'base hook' => 'block',
      'variables' => []
    ],
    'block__grow_business_with_planet' => [
      'template' => 'block--grow-business-with-planet',
      'base hook' => 'block',
      'variables' => []
    ],
    'block__grow_business_with_planet_large' => [
      'template' => 'block--grow-business-with-planet-large',
      'base hook' => 'block',
      'variables' => []
    ],
    'block__case_studies_more' => [
      'template' => 'block--case-studies-more',
      'base hook' => 'block',
      'variables' => []
    ],
    'block__case_studies_request_demo' => [
      'template' => 'block--case-studies-request-demo',
      'base hook' => 'block',
      'variables' => []
    ],
    'form__exposed_case_studies' => [
      'template' => 'form--exposed-case-studies',
      'base hook' => 'form',
      'variables' => []
    ],
    'views_view_fields__planet_case_studies_view_load_more__block_1__page' => [
      'template' => 'views-view-fields--planet-case-studies-view-load-more--block-1--page',
      'base hook' => 'views_view_fields',
      'variables' => []
    ],
  ];

  return $array;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function planet_case_studies_preprocess_node(array &$variables) {
  $node = $variables['node'];
  $case_studies_helper = \Drupal::getContainer()
    ->get('planet_core.case_studies_helper');

  if (_is_path_case_studies_landing()) {
    $variables['case_studies'] = $case_studies_helper->getAllCaseStudies();
    $variables['brands'] = \Drupal::service('planet_core.case_studies_helper')
      ->getBrandsWeWorkWith();
  }

  if ($node->getType() === 'case_studies') {
    $node_translation_service = \Drupal::getContainer()->get('planet_core.node_translation_service');
    $contact_sales_this_languge_url = $node_translation_service->getTranslationArrWithPrefixes('/contact/sales');
    $lang_id = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $variables['contact_sales_url'] = $contact_sales_this_languge_url[$lang_id] ?? $contact_sales_this_languge_url['en'];
    $variables['case_studies_url'] = _get_case_studies_url();

    $variables['case_study_data'] = $case_studies_helper->getSingleCaseStudyData($node);
    $variables['case_studies'] = $case_studies_helper->getCaseStudiesForMoreBlock(0, 4, $variables['case_study_data']['products'], $variables['case_study_data']['industry'], $variables['case_study_data']['company_size']);

    $media_id = NULL;

    if (isset($node->get('field_video_media')?->getValue()[0])) {
      $media_id = $node->get('field_video_media')?->getValue()[0]['target_id'];
    }

    if (!is_null($media_id) && isset($node->get('field_video_media')
          ?->getValue()[0])) {
      $media = \Drupal::entityTypeManager()
        ->getStorage('media')
        ->load($media_id);
      if ($media->hasField('field_media_oembed_video')) {
        if ($media->get('field_media_oembed_video')?->getValue()[0]['value']) {
          $unprocessed_url = $media->get('field_media_oembed_video')
            ?->getValue()[0]['value'];

          if (str_starts_with($unprocessed_url, 'https://www.youtube.com/watch?v')) {
            $queryString = parse_url($unprocessed_url, PHP_URL_QUERY);

            parse_str($queryString, $queryParams);
            $param = $queryParams['v'];
          }
          else {
            $param = implode(array_slice(str_split($unprocessed_url), 17, 11));
          }

          $final_url = 'https://www.youtube-nocookie.com/embed/' . $param;
          $variables['case_study_data']['oembed_url'] = $final_url;
          $variables['case_study_data']['video_subtext'] = $node->get('field_video_subtext')
            ?->getValue()[0]['value'];
        }
      }
    }
  }
}


/**
 * Gets the case studies URL for a current language.
 */
function _get_case_studies_url() {
  $node_translation_service = \Drupal::getContainer()->get('planet_core.node_translation_service');
  $lang_id = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $case_study_url = $node_translation_service->getTranslationArrWithPrefixes('/case-studies');

  return $case_study_url[$lang_id] ?? $case_study_url['en'];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function planet_case_studies_preprocess_select(array &$variables) {
  $variables['element']['#attributes']['class'][] = 'form-select';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function planet_case_studies_preprocess_page(array &$variables) {
  if (_is_path_case_studies_landing()) {
    $variables['#attached']['library'][] = 'planet_case_studies/planet_case_studies';
    $variables['#attached']['library'][] = 'planet_core/swiper-bundle';
  }

  $node = \Drupal::routeMatch()->getParameter('node');

  if ($node instanceof NodeInterface) {
    if ($node->getType() === 'case_studies') {
      $variables['#attached']['library'][] = 'planet_case_studies/planet_case_study';
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function planet_case_studies_theme_suggestions_node_alter(array &$suggestions, array &$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');

  if (!$node or !($node instanceof NodeInterface)) {
    return;
  }

  if (_is_path_case_studies_landing()) {
    $suggestions[] = 'node__case_studies_landing';
  }

  if ($node->getType() === 'case_studies') {
    $suggestions[] = 'node__case_studies';
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function planet_case_studies_theme_suggestions_views_view_fields_alter(&$suggestions, &$variables) {
  if (_is_path_case_studies_landing()) {
    $view_id = $variables['view']->id();
    $display_id = $variables['view']->current_display;

    // Add cache context for path awareness.
    \Drupal::service('renderer')
      ->addCacheableDependency($variables, ['#cache' => ['contexts' => ['url.path']]]);

    $node = \Drupal::routeMatch()->getParameter('node');

    if (!$node or !($node instanceof NodeInterface)) {
      return;
    }

    $suggestions[] = 'views_view_fields__' . $view_id . '__' . $display_id . '__' . $node->getType();
    $suggestions[] = 'views_view_fields__' . $view_id . '__' . $display_id . '__' . $node->id();
  }
}

function _is_path_case_studies_landing() {
  $paths = [
    '/case-studies',
    '/es/casos-exito',
    '/fr/etudes-de-cas',
    '/it/storie-successo',
    '/de/fallstudien',
  ];

  $path = \Drupal::service('path.current')->getPath();
  $current_path_alias = \Drupal::service('path_alias.manager')
    ->getAliasByPath($path);
  $current_language = \Drupal::languageManager()->getCurrentLanguage()->getId();

  if (in_array($current_path_alias, $paths) || in_array("/$current_language" . "$current_path_alias", $paths)) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function planet_case_studies_theme_suggestions_select_alter(&$suggestions, &$variables) {
  $fields = [
    'edit-field-product-type-target-id',
    'edit-field-industry-type-target-id',
    'edit-field-company-size-target-id',
  ];

  if (in_array($variables['element']['#id'], $fields)) {
    $suggestions[] = 'select__case_studies';
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function planet_case_studies_theme_suggestions_form_alter(&$suggestions, &$variables) {
  if (isset($variables['element']['#id'])) {
    if ($variables['element']['#id'] === 'views-exposed-form-planet-case-studies-view-load-more-block-1') {
      $suggestions[] = 'form__exposed_case_studies';
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function planet_case_studies_form_alter(&$form, FormStateInterface $form_state) {
  $lang_id = \Drupal::languageManager()->getCurrentLanguage()->getId();

  if ($form['#id'] === 'views-exposed-form-planet-case-studies-view-load-more-block-1') {
    $form['field_product_type_target_id']['#options']['All'] = \Drupal::getContainer()->get('planet_core.node_translation_service')->t2('All products', [], $lang_id);;
    $form['field_industry_type_target_id']['#options']['All'] = \Drupal::getContainer()->get('planet_core.node_translation_service')->t2('All industries', [], $lang_id);;
    $form['field_company_size_target_id']['#options']['All'] = \Drupal::getContainer()->get('planet_core.node_translation_service')->t2('All companies', [], $lang_id);;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * We need to disable the submit action on the exposed form.
 */
function planet_case_studies_form_views_exposed_form_alter(&$form, FormStateInterface $form_state) {
  if (_is_path_case_studies_landing()) {
    $form['actions']['submit']['#attributes']['disabled'] = 'disabled';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function planet_case_studies_preprocess_views_view_fields(&$variables) {
  if (_is_path_case_studies_landing()) {
    $node = $variables['row']->_entity;

    $media_id = $node->get('field_main_image_media')
      ?->getValue()[0]['target_id'];
    $styled_image_url = \Drupal::getContainer()
      ->get('planet_core.media_service')
      ->getStyledImageUrl($media_id, 'wide');

    $media_logo_id = $node->get('field_logo_media')
      ?->getValue()[0]['target_id'];
    $styled_logo_image_url = \Drupal::getContainer()
      ->get('planet_core.media_service')
      ->getImageUrl($media_logo_id, 'field_media_image');
    $variables['main_image_url'] = $styled_image_url;
    $variables['logo_image_url'] = $styled_logo_image_url;

    $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $variables['node_url'] = $lang !== 'en' ? "/$lang" . \Drupal::service('path_alias.manager')
        ->getAliasByPath('/node/' . $node->id()) : \Drupal::service('path_alias.manager')
      ->getAliasByPath('/node/' . $node->id());

    $landing_page_display_style = $node->get('field_landing_page_display_style')->value ? $node->get('field_landing_page_display_style')->value : 'pink';
    $variables['landing_page_display_style'] = $landing_page_display_style;
    $variables['triplet_img_class'] = $variables['row']->triplet_img_class;
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function planet_case_studies_preprocess_views_view(&$variables) {
  if (_is_path_case_studies_landing()) {
    $rows = $variables['view']->result;

    foreach ($rows as $index => $row) {
      $triplet_n = floor(($index / 3));
      $position_in_a_triplet = $index % 3;
      $rows[$index]->counter = $index + 1;

      if ($triplet_n % 2 == 0) {
        if ($position_in_a_triplet == 0) {
          $rows[$index]->triplet_img_class = 'large-left';
        }
        else {
          switch ($position_in_a_triplet) {
            case 1:
              $rows[$index]->triplet_img_class = 'small-right-top';
              break;
            case 2:
              $rows[$index]->triplet_img_class = 'small-right-bottom';
              break;
          }
        }
      }
      else {
        if ($position_in_a_triplet == 2) {
          $rows[$index]->triplet_img_class = 'large-right';
        }
        else {
          switch ($position_in_a_triplet) {
            case 0:
              $rows[$index]->triplet_img_class = 'small-left-top';
              break;
            case 1:
              $rows[$index]->triplet_img_class = 'small-left-bottom';
              break;
          }
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_views_rows_wrapper().
 */
function planet_case_studies_preprocess_views_rows_wprapper(&$variables) {
  if (_is_path_case_studies_landing()) {
    $variables['rows'] = $variables['view']->result;
  }
}
