<?php

use Drupal\Core\Url;
use Drupal\node\NodeInterface;


function planet_partners_pages_theme_suggestions_node_alter(array &$suggestions, array $variables)
{
  $node = \Drupal::routeMatch()->getParameter('node');
 
  if (!$node || !($node instanceof NodeInterface)) {
    return;
  }

  $path_alias_manager = \Drupal::service('path_alias.manager');
  $alias = $path_alias_manager->getAliasByPath('/node/' . $node->id());

  if ($alias === '/partners-pages-new') {
    $suggestions[] = 'node__partners-page';
  }

  if ($node->getType() === 'partners') {
    $suggestions[] = 'node__partners-single-page';
  }
}

function planet_partners_pages_theme(): array
{
  return [
    'node__partners-page' => [
      'template' => 'node--partners-page',
      'base hook' => 'node',
    ],
    'node__partners-single-page' => [
      'template' => 'node--partners-single-page',
      'base hook' => 'node',
    ],
  ];
}

function planet_partners_pages_preprocess_node(array &$variables)
{
  $node = $variables['node'];
  $path_alias_manager = \Drupal::service('path_alias.manager');
  $alias = $path_alias_manager->getAliasByPath('/node/' . $node->id());
  if ($node->getType() == 'partners') {

  $planet_core_partners_helper = \Drupal::service('planet_partners_pages.partners_helper');
  $node_translation_service = \Drupal::service('planet_core.node_translation_service');

    $variables['article'] = $planet_core_partners_helper->getSinglePartnerData($node->id());
    $variables['langcode'] = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $variables['main_link'] = $node_translation_service->getTranslationArrWithPrefixes('/partners');
    $variables['#attached']['library'][] = 'planet_core/basic-pages';
    $variables['#attached']['library'][] = 'planet_partners_pages/partners-page';


    $page_service = \Drupal::service('planet_core.basic_page_service');
    $variables['product_page_paragraphs'] = $page_service->getPageParagraphData($node);

    if(!$node->get('field_partners_webform')->isEmpty()) {
      $webform_id = $node->get('field_partners_webform')->target_id;
      $form = \Drupal::entityTypeManager()
          ->getStorage('webform')
          ->load($webform_id)
          ->getSubmissionForm();
      $variables['form'] = $form;
  }
  return;
}

  if ($alias === '/partners-pages-new') {
    $planet_core_partners_helper = \Drupal::service('planet_partners_pages.partners_helper');
    $variables['taxonomy_type'] = $planet_core_partners_helper->getPartnersTaxonomy('partner_type');
    $variables['taxonomy_industry'] = $planet_core_partners_helper->getPartnersTaxonomy('industry');
    $variables['taxonomy_product'] = $planet_core_partners_helper->getPartnersTaxonomy('product_type');
    $variables['taxonomy_region'] = $planet_core_partners_helper->getPartnersTaxonomy('region');
    $variables['#attached']['library'][] = 'planet_partners_pages/partners-page';
  }
}
