<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Primary module hooks for planet_translation_field_populator.permissions.yml module.
 */


function planet_translation_field_populator_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $path_alias = \Drupal::service('path_alias.manager')->getAliasByPath(\Drupal::service('path.current')->getPath());
  $username = Drupal::currentUser()->getAccountName();

  if ($path_alias === '/admin/planet/populator') {
    if (!(\Drupal::currentUser()->hasPermission('access_populator') && in_array($username, ['adam.youssef', 'florin.cotovanu']))) {
      $form = [
        '#parents' => [],
        '#markup' => t('Access Denied.'),
      ];
    }
  }
}
