<?php

/**
 * @file
 * Custom hooks functions for the planet_language_switcher module.
 */

 function get_author_articles($authorId) {
  $query = \Drupal::entityQuery('node')
    ->condition('type', 'resources') // Adjust to your content type name.
    ->condition('field_author.target_id', $authorId);

  $resource_nids = $query->execute();
  $resource_nodes = \Drupal\node\Entity\Node::loadMultiple($resource_nids);

  $articles = [];

  foreach ($resource_nodes as $node) {
    // Assuming the title is in the 'title' field.
    $title = $node->getTitle();
    // Get the URL for the canonical path of the node.
    $url = \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $node->id());

    $articles[] = [
      'url' => $url,
      'title' => $title,
    ];
  }

  return $articles;
}

/**
 * Implements hook_preprocess_HOOK() for node templates.
 */
function planet_language_switcher_preprocess_node__author(&$variables) {
  // Get the last 5 article titles.
  $node = $variables['node'];

  // Get the NID (node ID) of the Author node.
  $node_id = $node->id();

  $article_titles = get_author_articles($node_id);

  // Pass the titles to the template.
  $variables['articles'] = $article_titles;
}
/**
 * Implements hook_theme().
 */
function planet_language_switcher_theme() {
  return [
    'language_switcher' => [
      'variables' => ['data' => []],
    ],
    'node__author' => [
      'template' => 'node--author',
      'base hook' => 'node'
    ],
  ];
}
