<?php


function planet_language_switcher_preprocess_html(&$variables) {
  /** Where to display the transparent header */
  $allowed_pages = [
    "author"
  ];
  $node = \Drupal::routeMatch()->getParameter('node');

  if ($node && in_array($node->bundle(), $allowed_pages)) {
    $variables['attributes']['class'][] = "planet-header-transparent";
  }
  
}

/**
 * Implements hook_preprocess_HOOK() for node templates.
 */
function planet_language_switcher_preprocess_node__author(&$variables) {
  // Get the last 5 article titles.
  $node = $variables['node'];

  // Get the NID (node ID) of the Author node.
  $node_id = $node->id();

  $author_data = planet_core_get_author_articles($node_id);

  // Pass the titles to the template.
  $variables['author_data'] = $author_data;
}
/**
 * Implements hook_theme().
 */
function planet_language_switcher_theme() {
  return [
    'language_switcher' => [
      'variables' => ['data' => []],
    ],
    'onboarding_page_template' => [
      'variables' => ['content' => NULL],
      'template' => 'page--onboarding-page-template',
      'base hook' => 'page',
    ],
  ];
}

// function log_to_file($text)
// {
//   $f = fopen('my_log.txt', 'a');
//   fwrite($f, date('Ymd H:i:s - ') . $text . "\n");
//   fclose($f);
// }

/**
 * Implements hook_theme_suggestions_HOOK_alter() to suggest a custom template for a specific node.
 */
function planet_language_switcher_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $node = \Drupal::routeMatch()->getParameter('node');

  if(!$node) {
    return;
  }
  
  $alias = \Drupal::service('path_alias.manager')->getAliasByPath('/node/'.$node->id());

  /** Onboarding page tempalte */
  if ($node instanceof \Drupal\node\NodeInterface && $alias == "/customer-resources-tobe") {
    $suggestions[] = 'onboarding_page_template';
  }
}