name: CI

on:
  push:
    branches: [ PLNT-0000-github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: ls -al
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.0"
          version: 2.x
          args: --ignore-platform-reqs
      - name: Pushes to acquia repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_AUT }}
        with:
          source-directory: 'output'
          destination-github-username: 'rzanetti'
          destination-repository-name: 'planetpayment@svn-41605.prod.hosting.acquia.com:planetpayment.git'
          target-branch: main
