name: CI
on:
  push:
    branches: [ PLNT-0000-github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Test composer
        run: composer --no-ansi validate --no-check-lock
      - name: Run composer
        run: composer install --optimize-autoloader --ignore-platform-reqs
      - name: install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_AUT }}
          name: id_rsa
          known_hosts: planetpayment@svn-41605.prod.hosting.acquia.com:planetpayment.git
      - name: Clone acquia dev
        run: GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone -b dev --single-branch planetpayment@svn-41605.prod.hosting.acquia.com:planetpayment.git
      - name: Verify acquia info
        run: cd planetpayment && ls -al
      - name: Remove old files
        run: cd planetpayment && rm -rf config && rm -rf docroot && rm -rf vendor && rm -rf patches
      - name: copy files
        run: cp -R config ./planetpayment/ && cp -R docroot ./planetpayment/ && cp -R vendor ./planetpayment/ && cp -R patches ./planetpayment/ && cp composer.json ./planetpayment/ && cp composer.lock ./planetpayment/ && cp hooks ./planetpayment/
      - name: remove submodules git
        run: cd planetpayment && rm -rf docroot/modules/contrib/wb_countries/.git && rm -rf docroot/modules/contrib/webform_pardot/.git
      - name: add git info
        run: cd planetpayment && git config --global user.email "noreply@planetpayment.com" && git config --global user.name "CI Deploy"
      - name: add, commit and push
        run: cd planetpayment && git add config docroot vendor patches composer.json composer.lock hooks && git commit -m "dev deploy" && GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push
