name: CI
on:
  push:
    branches: [ PLNT-0000-github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_AUT }}
          name: id_rsa
          known_hosts: planetpayment@svn-41605.prod.hosting.acquia.com:planetpayment.git
      - name: Clone acquia repo
        run: GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone planetpayment@svn-41605.prod.hosting.acquia.com:planetpayment.git
      - name: Verify acquia info
        run: cd planetpayment && ls -al
