name: Build & Deploy Planet Weareplanet Website
run-name: Build and Deploy by @${{ github.actor }}.

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/weareplanet
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker_azure_storage/Dockerfile
          push: true
          tags: |
            ghcr.io/weareplanet/planet-lead-generation:latest
            ghcr.io/weareplanet/planet-lead-generation:${{ github.sha }}

  deploy_webapp:
    needs: build_image
    strategy:
      max-parallel: 1
      matrix:
        envs: [uat]
    environment:
      name: ${{ matrix.envs }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: read
      contents: read
      id-token: write

    steps:
      - name: Deploy WebApp to slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_APP_NAME }}
          slot-name: 'staging'
          images: 'ghcr.io/weareplanet/planet-lead-generation:${{ github.sha }}'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}