name: CI/CD for ML

on:
  push:
    branches: [ main ]

jobs:
  train-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install CML
        run: npm install -g @dvcorg/cml

      - name: Install Python build tools and dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          pip install -r requirements-ci.txt
      - name: Run training and generate report
        run: python train.py

      - name: Post report with CML
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create reports/report.md --token $REPO_TOKEN
