name: Manual deployment
 
on:
  workflow_dispatch:
    inputs:
      env:
        type: string
        default: uat
      image_tag:
        required: true
        type: string
 
jobs:
  deploy_webapp:
    environment:
      name: ${{ inputs.env }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: read
      contents: read
      id-token: write
 
    steps:
      - name: Deploy WebApp to slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_APP_NAME }}
          slot-name: 'staging'
          images: 'ghcr.io/weareplanet/planet-lead-generation:${{ inputs.image_tag }}'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}